addons:
  apt:
    sources:
      - git-core
    packages:
      - git

install:
- git --version
- openssl aes-256-cbc -K $encrypted_6626094401ff_key -iv $encrypted_6626094401ff_iv -in key.enc -out key -d
- chmod 600 ./key
- GIT_SSH_COMMAND='ssh -i ./key' git push git@github.com:SuperTux/supertux.wiki.git HEAD:master
