# Travis-CI build for pushing the SuperTux/wiki repository to the GitHub Wiki
# repository for the SuperTux/supertux project.

language: ruby

# Use containerized infrastructure, for faster builds.
sudo: false

addons:
  apt:
    sources:
      - git-core
    packages:
      - git

# Only push master branch to remote master.
branches:
  only:
    - master

install: true

script:
  - git --version
  - openssl aes-256-cbc -K $encrypted_6626094401ff_key -iv $encrypted_6626094401ff_iv -in key.enc -out key -d
  - chmod 600 ./key
  - GIT_SSH_COMMAND='ssh -i ./key' git push git@github.com:SuperTux/supertux.wiki.git HEAD:master
